version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: 'always'
    depends_on:
      - backend
      - db
  backend:
    build: ./backend
    restart: 'unless-stopped'
    links:
      - db
    depends_on:
      - db
    environment:
      - PORT=3001
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_NAME=women_soccer
      - DB_PORT=3306
    ports:
      - "3001:3001"
    networks:
      - db_back
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    networks:
      - db_back
    cap_add:
      - SYS_NICE
networks:
  db_back:
    driver: 'bridge'